### ISSUE TITLE
Multiple servers / relay system

### ISSUE THREAD

**Issue by mtz629** [daparker/checkvalve#1]
Does chat relay support multiple servers (ie, multiple srcds instances on the same physical box) without multiple instances of the chat relay server component itself?  Sorry if I missed this in the docs.  Thanks.

**Comment by daparker** [comment]
It does.  You can point as many game servers as you want at a single instance of the Chat Relay.  As part of the connection request, the client (i.e., CheckValve) specifies which game server it wants to receive relayed messages from.  When the Chat Relay receives a chat message from a game server, it checks to see if any client wants messages from that server.  If at least one client does, then it parses and relays the message.

Does this answer your question?

**Comment by mtz629** [comment]
Sorry for the late response.  Wandered away from this project and finally wandered back.  It does answer.  Thank you.
