### ISSUE TITLE
Show menu by touch on server

### ISSUE THREAD

**Issue by fant1kua** [daparker/checkvalve#6]
Please, show menu by single touch on server, but not long touch.
P.S.  sorry for my English.

**Comment by daparker** [comment]
Hello,

Thanks for the request.  Unfortunately, I don't know if this is a change I can make right away.  CheckValve uses Android's built-in Menu API, which uses the long-click as the activation event for a context menu.  So, it's not something I have explicitly coded, but rather something built-in to the API.

From the [Menu API documentation](http://developer.android.com/guide/topics/ui/menus.html#context-menu) for floating context menus:

> A menu appears as a floating list of menu items (similar to a dialog) when
> the user performs a long-click (press and hold) on a view that declares
> support for a context menu.

When I have the time, I will play around with other options and see if I can override the default behavior.  But for now, I don't think I can change this.
